name: Build, Test, and Deploy to Cloud Run

on:
  push:
    branches:
      - kevin

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Build with Maven
        working-directory: rest-client-quickstart
        env:
          MP_JWT_VERIFY_PUBLICKEY: ${{ secrets.PUBLIC_KEY }}
          SMALLRYE_JWT_SIGN_KEY: ${{ secrets.PRIVATE_KEY }} 
        run: ./mvnw clean package -Dnative

      - name: List target directory
        working-directory: rest-client-quickstart
        run: ls -la target

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        working-directory: rest-client-quickstart
        run: |
          docker build -f src/main/docker/Dockerfile.native-micro -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/runner:latest .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/runner:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: quarkus-rest-client-quickstart
          image: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/runner:latest
          region: europe-north1
          flags: |
            --allow-unauthenticated
            --port=8080
            --min-instances=1
            --cpu=1
            --memory=512Mi
          secrets: |
            MP_JWT_VERIFY_ISSUER=${{ secrets.JWT_VERIFY_ISSUER }}
            MP_JWT_VERIFY_PUBLICKEY=${{ secrets.PUBLIC_KEY }}
            SMALLRYE_JWT_SIGN_KEY=${{ secrets.PRIVATE_KEY }}
