name: Build, Test, and Deploy to Cloud Run

on:
  push:
    branches:
      - kevin

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'fetch-secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |
            MP_JWT_VERIFY_PUBLICKEY:projects/cs-devops-62582-group8/secrets/public_key
            SMALLRYE_JWT_SIGN_KEY:projects/cs-devops-62582-group8/secrets/private_key

      - name: Build with Maven
        working-directory: rest-client-quickstart
        env:
          MP_JWT_VERIFY_PUBLICKEY: ${{ steps.fetch-secrets.outputs.MP_JWT_VERIFY_PUBLICKEY }}
          SMALLRYE_JWT_SIGN_KEY: ${{ steps.fetch-secrets.outputs.SMALLRYE_JWT_SIGN_KEY }}
        run: ./mvnw clean package -Dquarkus.profile=prod

      - name: List target directory
        working-directory: rest-client-quickstart
        run: ls -la target

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        working-directory: rest-client-quickstart
        env:
          MP_JWT_VERIFY_PUBLICKEY: ${{ steps.fetch-secrets.outputs.MP_JWT_VERIFY_PUBLICKEY }}
          SMALLRYE_JWT_SIGN_KEY: ${{ steps.fetch-secrets.outputs.privSMALLRYE_JWT_SIGN_KEYate_key }}
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/runner:latest .


      - name: Push Docker image to Google Container Registry
        run: |
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/runner:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: quarkus-rest-client-quickstart
          image: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/runner:latest
          region: europe-north1
          flags: |
            --allow-unauthenticated
            --timeout=600s
          env_vars: |
            MP_JWT_VERIFY_ISSUER = ${{ secrets.JWT_VERIFY_ISSUER }} 
