name: Build, Test, and Deploy to Cloud Run

on:
  push:
    branches:
      - kevin

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: rest-client-quickstart/src/main/docker/Dockerfile.native-micro
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/quarkus-rest-client-quickstart:latest
  
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: quarkus-rest-client-quickstart
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/quarkus-rest-client-quickstart:latest
          region: europe-north1
          flags: '--allow-unauthenticated'
          env_vars: |
            PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}

      - name: Run Post-Deployment Scripts
        working-directory: script/prod
        run: |
          ./prod/build.sh
          ./prod/run.sh
